### ISSUE TITLE
Cannot build atlas-orca standalone; cannot find NetCDF

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/atlas-orca#7]
I am trying to build atlas-orca standalone, it is failing like this:

CMake Error at /home/h01/frwd/cylc-run/mi-be204/share/installs/ecbuild/share/ecbuild/cmake/ecbuild_log.cmake:190 (message):
  [1;35mCRITICAL - Feature NETCDF cannot be enabled -- following required
  packages weren't found: NetCDF[m
Call Stack (most recent call first):
  /home/h01/frwd/cylc-run/mi-be204/share/installs/ecbuild/share/ecbuild/cmake/ecbuild_add_option.cmake:260 (ecbuild_critical)
  src/apps/atlas-orca-convert/CMakeLists.txt:16 (ecbuild_add_option)

My NetCDF is built in separate directories for C, C++ and Fortran.  The relevant NetCDF -config scripts are in the $PATH.

I think this can be fixed by using a tweaked find NetCDF script (such as that used by jedi-cmake) but is there another alternative?

**Comment by wdeconinck** [comment]
Hi @DJDavies2 
NetCDF is not a required feature and is not linked at all in to the atlas-orca plugin.
It is only used to compile an executable that is used in the process to generate a new supported ORCA grid.
If you need this, which I doubt, and the issue is about finding NetCDF, it should be a ecbuild issue instead.
I thought ecbuild PR https://github.com/ecmwf/ecbuild/pull/26 would have fixed that?
Try to see if you get example project https://github.com/ecmwf/ecbuild/blob/develop/examples/find_package/find_netcdf.sh to work with latest ecbuild version.

**Comment by DJDavies2** [comment]
Okay, I've opened an ecbuild issue (https://github.com/ecmwf/ecbuild/issues/46).  I think there is a problem with ecbuild's FindNetCDF.cmake.  I have found some hacks as well that allow building with current ecbuild.

**Comment by wdeconinck** [comment]
Thank you. ecbuild "develop" has been updated with your fix. ecbuild 3.8.0 will be the first release with this fix included.
